name: linux_system_info
description: Dart library for getting linux system information like parsed /etc/os-release, cpu usage, cpu information, cores information, memory information, kernel information and os information
version: 0.0.2
homepage: https://github.com/LolzDEV/linux_system_info

environment:
  sdk: '>=2.10.0 <3.0.0'


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies:
  tuple: ^2.0.0
